Modal
heorhii-aksiuk/team-proj-html-css pull request #60
Opened 2021-07-06 16:04 UTC by ITValerka

Made modal window

2021-07-06 16:58 UTC, heorhii-aksiuk commented
Что это вообще такое?
![image](https://user-images.githubusercontent.com/81520242/124639131-771f5400-de94-11eb-9610-d468e8c2a6e8.png)

2021-07-06 16:59 UTC, heorhii-aksiuk requested changes
Что это такое и зачем? У нас нет этой модалки в макете, это модалка с домашки. У нас только модальное меню

2021-07-06 17:40 UTC, ITValerka commented
Кнопка “Консультация по телефону” открывает модальное окно с формой заказа. Так как дизайна модального окна нет на макете, это является не обязательным заданием.

2021-07-06 17:41 UTC, ITValerka commented
Не обязательно, но если есть возможность, почему бы и нет.

2021-07-06 17:52 UTC, heorhii-aksiuk commented
Твоё окно вообще не в дизайн с макетом, там лишние формы мейла и комментариев, там лишний пункт договора, оно на русском языке и оно кривое и не работает.
Если и делать модалку, то какую-то такую
![image](https://user-images.githubusercontent.com/81520242/124645162-c61cb780-de9b-11eb-85d9-79337fc230ea.png)

2021-07-07 12:57 UTC, Iurii-P commented
а мне нравится модалка +

2021-07-07 12:57 UTC, Iurii-P approved these changes

2021-07-07 17:49 UTC, closed without merging

2021-07-07 17:50 UTC, ITValerka commented
delete